version: "3.8"
services:
  backend:
    image: "ninanitzsche/springboot-react-fullstack:16.12.2021.8.59.53"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
