version: "3.8"
services:
  backend:
    image: "ninanitzsche/springboot-react-fullstack:17.12.2021.7.54.27"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
